apiVersion: v1
data:
  server.yaml: |
    address: https://vault.travelaudience.com
    auth:
      type: kubernetes
      backend: training-235717-gke-1
      data:
        role: time-server
    mode:
      name: initC
      data:
        pki:
          - mountName: intermediate-ca
            role: time-server
            cn: time-server.default.svc.cluster.local
            sans:
            - time-server.default
            - time-server
            - localhost
            - 127.0.0.1
            cnIsIdentifier: false
            mountDir: /secret
  client.yaml: |
    address: https://vault.travelaudience.com
    auth:
      type: kubernetes
      backend: training-235717-gke-1
      data:
        role: time-server
    mode:
      name: initC
      data:
        pki:
          - mountName: intermediate-ca
            role: time-client
            cn: time-client
            cnIsIdentifier: true
            mountDir: /secret
kind: ConfigMap
metadata:
  name: kubernetes-vault-client-03
