apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: time
    role: client
  name: time-client
  namespace: kubernetes-vault-example-01
spec:
  selector:
    matchLabels:
      app: time
      role: client
  serviceName: time-client-set
  replicas: 1
  template:
    metadata:
      labels:
        app: time
        role: client
    spec:
      containers:
      - name: client
        image: eu.gcr.io/kubernetes-vault-example/time-client:1.0-01
        imagePullPolicy: Always
