apiVersion: v1
data:
  config.yaml: |
    address: https://vault.travelaudience.com
    auth:
      type: kubernetes
      backend: training-235717-gke-1
      data:
        role: time-server
    mode:
      name: initC
      data:
        kv:
          - path: secret/time-server-credentials
            key: username
            mountPath: /secret/username
          - path: secret/time-server-credentials
            key: password
            mountPath: /secret/password
kind: ConfigMap
metadata:
  name: kubernetes-vault-client-02
